# Generated by Django 4.1.5 on 2023-01-20 11:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DollarByBtc",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("calculation_date", models.DateTimeField(verbose_name="Дата Расчета")),
                (
                    "btc_rate",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Курс Биткойна",
                    ),
                ),
                (
                    "assets_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Стоимость чистых активов",
                    ),
                ),
                (
                    "pnl",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Текущиий PnL"
                    ),
                ),
                ("index_pnl", models.FloatField(verbose_name="Текущии Index PnL")),
            ],
        ),
    ]
