# Generated by Django 4.1.5 on 2023-01-20 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency_rate", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DollarByBtc",
            new_name="BtcRecords",
        ),
    ]
