# Generated by Django 4.1.5 on 2023-01-20 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("currency_rate", "0002_rename_dollarbybtc_btcrecords"),
    ]

    operations = [
        migrations.RenameField(
            model_name="btcrecords",
            old_name="btc_rate",
            new_name="btc_price",
        ),
    ]
